# Basic application configuration
app:
  name: MyApp
  version: 1.0.0
  environment: development

# Database settings
database:
  host: localhost
  port: 5432
  name: myapp_db
  user: db_user
  password: secret_password

# List of services
services:
  - name: web
    port: 8080
    enabled: true

  - name: api
    port: 8081
    enabled: false

  - name: worker
    port: 8082
    enabled: true

# Logging configuration
logging:
  level: info
  file: /var/log/myapp.log

# Features toggle
features:
  auth: true
  payments: false
  analytics: true
